logging:
  level:
    root: WARN
    co:
      chlg:
        javaimpdec: INFO
    org:
      springframework:
        web: ERROR
  pattern:
    console: '%n%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg'